{% set name = "publish" %}
{% set version = "1.0.1" %}
{% set sha256 = "575f513561ed6d7eb85ec1d55844c022bf4a70734b35a9b2be84bc251b42cfbc" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: "{{ name }}_version_{{ version }}.tar.gz"
  url: https://github.com/doconce/{{ name }}/archive/{{ name }}_version_{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 1003
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python
  host:
    - python
    - pip
  run:
    - python
    - lxml
    - future
    - python-levenshtein

test:
  imports:
    - publish

  commands:
    - publish --help

about:
  home: https://github.com/doconce/publish
  license: GPL-3.0-or-later
  license_family: GPL3
  license_file: COPYING
  summary: 'publish: a bibliographic reference system'

  description: |
    Publish may be used for handling publication lists for research
    institutions and departments, or for individual
    researchers. Publish imports publication metadata (title, author,
    year of publication etc), validates the imported data against a
    database of known venues, checks for missing attributes, corrects
    common errors etc, and allows simple filtering and generation of
    publication lists.
  doc_url: https://github.com/doconce/publish
  dev_url: https://github.com/doconce/publish

extra:
  recipe-maintainers:
    - johannesring
    - kghustad
